* CLAMPS

  Common Lisp Aided Music Production System

** Overview

   Clamps, short for "Common Lisp Aided Music Production System", is a
   software system for realtime and non-realtime music production
   written in Common Lisp. It enables a seamless workflow between
   high-level structures to define musical processes all the way down
   to low level dsp definitions for sound creation including browser
   based interfaces for interactive work and control useable for live
   performances. In that respect it combines features of systems like
   OpenMusic, SuperCollider or the Pure Data/Max family of software.

   The components of Clamps rely on and extend software not written by
   the author. The most important are:

   - [[#Incudine.overview][Incudine]]
     
   - [[Common Music][Common Music]]

   - [[FOMUS][FOMUS]]

   - [[ATS][ATS]]
     
   - [[CLOG][CLOG]]

** Installation

   To simplify the installation process, a separat repository
   [[https://github.com/ormf/clamps-install][clamps-install]] has been created. Please consult the installation
   instructions there.

** Documentation

   For Documentation refer to the =doc= folder in this
   repository. There is a compressed archive containing all
   documentation as cross-referenced HTML.

   Alternatively, to get an overview, see [[https://github.com/ormf/clamps/blob/main/doc/overview.org][doc/overview.org]]. More
   specific information about the packages can be obtained from
   [[https://github.com/ormf/clamps/blob/main/doc/clamps.org][doc/clamps.org]]. [[https://github.com/ormf/clamps/blob/main/doc/clamps-dictionary.org][clamps-dictionary.org]] contains an API reference
   with examples.

   Please note that the documentation currently is in progress as
   clamps hasn't been officially released yet.
