* CLAMPS

  Common Lisp Aided Music Production System

** Overview

   clamps is a system for realtime and non-realtime music production
   written in Common Lisp. It enables a seamless workflow between
   high-level structures to define musical processes all the way down
   to low level dsp definitions for sound creation including browser
   based interfaces for interactive work and control useable for live
   performances. In that respect it combines features of systems like
   OpenMusic, SuperCollider or the Pure Data/Max family of software.

   The components rely on and extend software not written by the
   author. The most important are listed under Dependencies.

   There is extensive documentation contained in the repository. To
   browse the documentation online use this link:

   [[Online doc not yet available]]

** Installation

   To simplify the installation process, a separat repository
   [[https://github.com/ormf/clamps-install][clamps-install]] has been created. Please consult the installation
   instructions there.

** Prerequisites

   - Jack

   - SBCL

   - Quicklisp

   - Gnu Emacs

   - git
** Dependencies

   - Incudine

     Used for sample accurate scheduling, the definition of the DSP
     parts and realtime IO (Audio, MIDI, OSC...).

   - Common Music (including FOMUS)

     Used as a high level interface for algorithmic composition,
     im/export from/to MIDI, SVG, Notation and realtime output (using
     incudine).

   - CLOG

     Used for browser based interactive GUI definitions.
     
