#+TITLE: Clamps Dictionary
#+AUTHOR: Orm Finnendahl
#+LANGUAGE: en
#+OPTIONS: html5-fancy:t
#+OPTIONS: num:nil
#+OPTIONS: toc:2 h:3 html-multipage-join-empty-bodies:t
#+OPTIONS: html-multipage-split:toc
#+OPTIONS: html-multipage-toc-to-top:t
#+OPTIONS: html-multipage-export-directory:dictionary
#+OPTIONS: html-multipage-open:browser
#+OPTIONS: html-multipage-top-insert:"<div class=\"org-div-top-insert\">\n<a class=\"top-menu\" href=\"../overview/index.html\">Overview</a>\n<a class=\"top-menu\" href=\"../clamps/index.html\">Clamps</a>\n<a class=\"top-menu\" href=\"../cm/index.html\">CM Dictionary</a>\n<a class=\"top-menu top-menu-active\" href=\"./index.html\">Clamps Dictionary</a>\n</div>\n"



# #+OPTIONS: html-multipage-include-default-style:t
#+HTML_DOCTYPE: xhtml5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/of-doc.css" />
#+HTML_HEAD: <link href="./pagefind/pagefind-ui.css" rel="stylesheet">
#+HTML_HEAD: <script src="./pagefind/pagefind-ui.js"></script>
#+INFOJS_OPT: path:./js/of-doc.js
# #+SETUPFILE: theme-readtheorg-local.setup
# \[\[\([^\[]+\)\]\] → [[\1][\1]]

* A
** ats->browser
   Function
   #+BEGIN_SRC lisp
   (ats->browser ats)
   #+END_SRC
   Display the =ats= struct graphically in the interactive ATS Player
   located at [[clamps-base-url][clamps-base-url]]/ats-display in the Gui.
* B
* C
** clamps
   Function
   #+BEGIN_SRC lisp
     (clamps &key (gui-base "/tmp/") (start-gui t))
   #+END_SRC
   Start Clamps including the gui.

   =gui-base= ist the path where to put the =www= subfolder for files
   accessible by the gui. In the given path the following directories
   will be created:

   - =gui-base/www/svg=

     file path for svg files used in the =svg-display= page of the
     Gui.

     Any files which need to be accessible by the Gui have to be put
     into the =gui-base/www= subdirectory with their filenames relative
     to this directory.
   
*** See also:

    - [[clamps-restart-gui][clamps-restart-gui]]
    - [[clamps-gui-root][clamps-gui-root]]
** clamps-base-url
   The url to access the Clamps Gui. Its default location is
   http://localhost:8080.
** clamps-restart-gui
   Function
   #+BEGIN_SRC lisp
     (clamps-restart-gui gui-base &key (start-gui t))
   #+END_SRC
   Reset the gui-root to =gui-base/www/=, optionally starting the
   Gui.

   =gui-base= ist the path where to put the =www= subfolder for files
   accessible by the Gui. In the given path the following directories
   will be created:

   - =gui-base/www/svg=

     file path for svg files used in the =svg-display= page of the
     Gui.

   Any files which need to be accessible by the Gui have to be put
   into the =gui-base/www= subdirectory with their filenames relative
   to this directory.

   
*** See also:

    - [[clamps][clamps]]
    - [[clamps-gui-root][clamps-gui-root]]

** clamps-gui-root
   Function
   #+BEGIN_SRC lisp
     (clamps-gui-root)
   #+END_SRC
   Return the pathname of the gui root.
*** See also:
    - [[clamps-restart-gui][clamps-restart-gui]]
* D
* E
* F
* G
* H
* I
* J
* K
* L
* M
* N
* O
* P
* Q
* R
* S
** set-bpm
   Function
   #+BEGIN_SRC lisp
   (set-bpm bpm)
   #+END_SRC
   Synonym for [[set-tempo][set-tempo]]
** set-tempo
   Function
   #+BEGIN_SRC lisp
   (set-tempo bpm)
   #+END_SRC
   Set the tempo in beats per minute for both, cm and incudine.
** svg->browser
   Function
   #+BEGIN_SRC lisp
   (svg->browser svg-file)
   #+END_SRC
   Display =svg-file= in the SVG Player Gui, located at
    [[clamps-base-url][clamps-base-url]]/svg-display

   =svg-file= is a string naming the svg-file to display/play. The
   filename is interpreted relative to the =gui-root/svg= directory.
* T
* U
* V
* W
* X
* Y
* Z
