#+TITLE: Clamps Dictionary
#+AUTHOR: Orm Finnendahl
#+LANGUAGE: en
#+startup: entitiespretty
#+OPTIONS: html5-fancy:t
#+OPTIONS: num:nil
#+OPTIONS: toc:2 h:3 html-multipage-join-empty-bodies:t
#+OPTIONS: html-multipage-split:2
#+OPTIONS: html-multipage-toc-to-top:t
#+OPTIONS: html-multipage-export-directory:clamps-dict
#+OPTIONS: html-multipage-open:nil
#+OPTIONS: html-preamble:"<a class=\"top-menu\" href=\"../overview/index.html\">Overview</a>\n<a class=\"top-menu\" href=\"../clamps/index.html\">Clamps</a>\n<a class=\"top-menu\" href=\"../cm-dict/index.html\">CM Dictionary</a>\n<a class=\"top-menu top-menu-active\" href=\"./index.html\">Clamps Dictionary</a>\n"
#+OPTIONS: html-toc-title:"Index"
#+OPTIONS: html-multipage-include-default-style:nil
#+HTML_DOCTYPE: xhtml5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/clamps-dictionary.css" />
#+HTML_HEAD: <link href="./pagefind/pagefind-ui.css" rel="stylesheet">
#+HTML_HEAD: <script src="./pagefind/pagefind-ui.js"></script>
# #+SETUPFILE: clamps-dict.setup
#+BIND: org-export-multipage-split-functions (export-dict-to-clamps)
# \[\[\([^\[]+\)\]\] → [[\1][\1]]
# C-x 8 RET 200b RET C-x 8 0

* A - B
** ats->browser
   Function
   #+BEGIN_SRC lisp
   (ats->browser ats)
   #+END_SRC
   Display the ats struct =ats= graphically in the interactive ATS
   Player located at /<clamps-base-url>/ats-display/ in the Gui.
*** See also:
    -  [[clamps-base-url][clamps-base-url]]
* C - H
** clamps
   Function
   #+BEGIN_SRC lisp
     (clamps &key (gui-root "/tmp/") (open t))
   #+END_SRC
   Start Clamps including the gui.

   =gui-root= ist the path where to put the /www/ subfolder for files
   accessible by the gui (nicknamed /<clamps-gui-root>/ throughout
   this dictionary).

   =open= is a flag indicating whether to open the [[clamps-base-url][clamps-base-url]] in
   a browser window after starting the gui.
   
   In the given path the following directories
   will be created:

   - /<clamps-gui-root>/www/
   - /<clamps-gui-root>/www/svg/
     
     file path for svg files used in the /<clamps-base-url>/svg-display/ page
     of the Gui.

   Any files which need to be accessible by the Gui have to be put
   into the /<clamps-gui-root>/www/ subdirectory with their filenames
   relative to this directory.
   
   Besides starting the Gui the function also:

   - Starts the osc responder for Inkscape
   - Starts the realtime engine calling [[rts][rts]]
   - Creates groups and buses for incudine dsps (see [[idump]] and the
     Chapter /Incudine extensions/ in [[../clamps/index.html][Clamps]])
   - Starts the documentation acceptor for the searchable online doc
     at /[[http://localhost:8282/overview][http://localhost:8282/overview]]//.

*** See also:
    - [[clamps-base-url][clamps-base-url]]
    - [[clamps-restart-gui][clamps-restart-gui]]
    - [[clamps-gui-root][clamps-gui-root]]
** clamps-base-url
   The base url to access the Clamps Gui (nicknamed /<clamps-base-url>/ in this
   dictionary).

   Its default location is http://localhost:56419.
*** Example:

    The location for the [[svg->browser][SVG Player Gui]] is at
    /<clamps-base-url>/svg-display/ which translates to the URL

    [[http://localhost:56419/svg-display]]


*** See also
    - [[clamps][clamps]]
    - [[clamps-restart-gui][clamps-restart-gui]]
    - [[clamps-gui-root][clamps-gui-root]]
** clamps-restart-gui
   Function
   #+BEGIN_SRC lisp
     (clamps-restart-gui gui-root &key (open t))
   #+END_SRC
   Reset the root directory of the Gui to /gui-root/www/, optionally
   opening the Gui in a browser window.

   =gui-root= ist the path where to put the /www/ subfolder for files
   accessible by the gui (nicknamed /<clamps-gui-root>/ throughout
   this dictionary).

   =open= is a flag indicating whether to open [[clamps-base-url][clamps-base-url]] in a
   browser window after starting the gui.
   
   In the given path the following directories
   will be created:

   - /<clamps-gui-root>/www/
   - /<clamps-gui-root>/www/svg/
     
     file path for svg files used in the /svg-display/ page of the
     Gui.

   Any files which need to be accessible by the Gui have to be put
   into the /<clamps-gui-root>/www/ subdirectory with their filenames
   relative to this directory.
*** See also:

    - [[clamps][clamps]]
    - [[clamps-base-url][clamps-base-url]]
    - [[clamps-gui-root][clamps-gui-root]]

** clamps-gui-root
   Function
   #+BEGIN_SRC lisp
     (clamps-gui-root)
   #+END_SRC
   Return the pathname of the Gui root directory. It is nicknamed
   /<clamps-gui-root>/ throughout this dictionary.

   /<clamps-gui-root>/ is the path corresponding to
   /<clamps-base-url>/ on the browser side, so any file named /<file>/
   put into the /<clamps-gui-root>/ directory can be accessed in the
   browser at the address /<clamps-base-url>/<file>/.
*** See also:
    - [[clamps][clamps]]
    - [[clamps-base-url][clamps-base-url]]
    - [[clamps-restart-gui][clamps-restart-gui]]
* I - M
** idump
   Function
   #+BEGIN_SRC lisp
     (idump node)
   #+END_SRC
   Dump all active dsps of /node/ to the /incudine:\ast{}logger-stream\ast{}/
   output.

   - =node= The id of the node
*** Note:
    If /(idump)/ doesn't create any output although dsps are running,
    reset the logger-stream using [[reset-logger-stream][reset-logger-stream]].
* N - Q
** node-free-unprotected
   Function
   #+BEGIN_SRC lisp
     (node-free-unprotected)
   #+END_SRC
   Free all Incudine nodes of /group 200/.
*** See also:
    - [[rts-hush][rts-hush]]
* R
** reset-logger-stream
   #+BEGIN_SRC lisp
     (reset-logger-stream)
   #+END_SRC
   Resets /incudine:*logger-stream*/ to /\ast{}error-output\ast{}/. Call this
   function, if calls to /incudine.util:msg/ don't produce any output
   in the REPL.

   This function needs to be called if /clamps/ is started from a Lisp
   Image.
** rts?
   Function
   #+BEGIN_SRC lisp
     (rts?)
   #+END_SRC
   Checks if rts is started and running.
*** See also:
    - [[rts][rts]]
** rts
   Function
   #+BEGIN_SRC lisp
     (rts (&key (rt-wait 0)))
   #+END_SRC
   Start the real time system of clamps. This functions sets the
   following special variables:

   =*midi-in1*= The default Midi Input

   =*midi-out1*= The default Midi Output

   =*rts-out*= The default output for realtime messages from
   clamps/cm.

   It also starts the rt engine of incudine calling
   /incudine:rt-start/.
*** See also:
    - [[rts?][rts?]]
** rts-hush
   Function
   #+BEGIN_SRC lisp
     (rts-hush)
   #+END_SRC
   Sends an all-notes-off message[fn:: See /ChannelModeMessages/ on [[https://midi.org/summary-of-midi-1-0-messages][this page]].] to all channels of /\ast{}​midi-out1\ast{}/ and
   calls [[node-free-unprotected][node-free-unprotected]].
*** Note:
    This command is bound to the Keyboard Sequence /<C-.>/ in emacs.
* S - Z
** set-bpm
   Function
   #+BEGIN_SRC lisp
   (set-bpm bpm)
   #+END_SRC
   Synonym for [[set-tempo][set-tempo]]
** set-tempo
   Function
   #+BEGIN_SRC lisp
   (set-tempo bpm)
   #+END_SRC
   Set the tempo in beats per minute for both, cm and incudine.
** svg->browser
   Function
   #+BEGIN_SRC lisp
   (svg->browser svg-file)
   #+END_SRC
   Display =svg-file= in the SVG Player Gui, located at
    /<clamps-base-url>/svg-display/.

   =svg-file= is a string naming the svg-file to display/play. The
   filename is interpreted relative to the /<clamps-gui-root>/svg/
   directory.
