(setq *clamps-fomus-symbols* (make-vector 63 0))
(mapcar
 (lambda (entry)
   (let ((symbol (intern (car entry)
			 *clamps-fomus-symbols*)))
     (if (boundp symbol)
	 (push (cadr entry) (symbol-value symbol))
       (set symbol (cdr entry)))))
 '(
   ("Downloading" "fomus/03_00_00_installation.html")
   ("Compiling/Loading" "fomus/03_02_00_compiling-loading.html")
   ("Installing as an Executable" "fomus/03_03_00_installing-as-an-executable.html")
   ("Customizing the Installation" "fomus/03_04_00_customizing-the-installation.html")
   ("Simple Emacs Interface" "fomus/03_05_00_simple-emacs-interface.html")
   ("Interface 1" "fomus/04_01_00_interface-1.html")
   ("Interface 2" "fomus/04_02_00_interface-2.html")
   ("Text File Interface" "fomus/04_03_00_text-file-interface.html")
   ("Common Music Interface" "fomus/04_04_00_common-music-interface.html")
   ("Command Line Interface" "fomus/04_05_00_command-line-interface.html")
   ("Chunks" "fomus/04_06_00_chunks.html")
   ("Other Interface Functions" "fomus/04_07_00_other-interface-functions.html")
   ("list-fomus-settings" "fomus/04_07_00_other-interface-functions.html")
   ("list-fomus-modules" "fomus/04_07_02_list-fomus-modules.html")
   ("list-fomus-instruments" "fomus/04_07_03_list-fomus-instruments.html")
   ("get-instr-syms" "fomus/04_07_04_get-instr-syms.html")
   ("list-fomus-percussion" "fomus/04_07_05_list-fomus-percussion.html")
   ("get-perc-syms" "fomus/04_07_06_get-perc-syms.html")
   ("list-fomus-instrgroups" "fomus/04_07_07_list-fomus-instrgroups.html")
   ("list-fomus-clefs" "fomus/04_07_08_list-fomus-clefs.html")
   ("list-fomus-meas-divs" "fomus/04_07_09_list-fomus-meas-divs.html")
   ("list-fomus-tuplet-divs" "fomus/04_07_10_list-fomus-tuplet-divs.html")
   ("load-init-file" "fomus/04_07_11_load-init-file.html")
   ("get-midi-instr" "fomus/04_07_12_get-midi-instr.html")
   ("marks" "fomus/04_07_13_marks.html")
   ("Class Part" "fomus/05_01_00_class-part.html")
   ("Methods" "fomus/05_01_01_methods.html")
   ("Accessors" "fomus/05_01_02_accessors.html")
   ("Class Timesig" "fomus/05_02_00_class-timesig.html")
   ("Methods" "fomus/05_02_01_methods.html")
   ("Accessors" "fomus/05_02_02_accessors.html")
   ("Class Timesig-repl" "fomus/05_03_00_class-timesig-repl.html")
   ("Methods" "fomus/05_03_01_methods.html")
   ("Class Keysig" "fomus/05_04_00_class-keysig.html")
   ("Class Note" "fomus/05_05_00_class-note.html")
   ("Methods" "fomus/05_05_01_methods.html")
   ("Accessors" "fomus/05_05_02_accessors.html")
   ("Class Rest" "fomus/05_06_00_class-rest.html")
   ("Methods" "fomus/05_06_01_methods.html")
   ("Accessors" "fomus/05_06_02_accessors.html")
   ("Class Mark" "fomus/05_07_00_class-mark.html")
   ("Methods" "fomus/05_07_01_methods.html")
   ("Accessors" "fomus/05_07_02_accessors.html")
   ("Structure Instr" "fomus/05_08_00_structure-instr.html")
   ("Methods" "fomus/05_08_01_methods.html")
   ("Accessors" "fomus/05_08_02_accessors.html")
   ("Structure Perc" "fomus/05_09_00_structure-perc.html")
   ("Methods" "fomus/05_09_00_structure-perc.html")
   ("Accessors" "fomus/05_09_02_accessors.html")
   ("Most useful Fomus Settings" "fomus/06_01_00_most-useful-fomus-settings.html")
   ("Complete Fomus Settings" "fomus/06_02_00_complete-fomus-settings.html")
   ("program settings" "fomus/06_02_00_complete-fomus-settings.html")
   ("backend options" "fomus/06_02_02_backend-options.html")
   ("global" "fomus/06_02_03_global.html")
   ("objects" "fomus/06_02_04_objects.html")
   ("parts" "fomus/06_02_05_parts.html")
   ("time signatures" "fomus/06_02_06_time-signatures.html")
   ("plugins" "fomus/06_02_07_plugins.html")
   ("plugins on/off" "fomus/06_02_08_plugins-on-off.html")
   ("quantizing" "fomus/06_02_09_quantizing.html")
   ("staves" "fomus/06_02_10_staves.html")
   ("ottavas" "fomus/06_02_11_ottavas.html")
   ("accidentals" "fomus/06_02_12_accidentals.html")
   ("cautionary accidentals" "fomus/06_02_13_cautionary-accidentals.html")
   ("grace notes" "fomus/06_02_14_grace-notes.html")
   ("measure/tuplet divisions" "fomus/06_02_15_measure-tuplet-divisions.html")
   ("note splitting/tying" "fomus/06_02_16_note-splitting-tying.html")
   ("beams" "fomus/06_02_17_beams.html")
   ("Alphabetical Listing of Settings" "fomus/06_03_00_alphabetical-listing-of-settings.html")
   ("Fomus Marks" "fomus/07_01_00_fomus-marks.html")
   ("Articulations" "fomus/07_01_01_articulations.html")
   ("Dynamics" "fomus/07_01_02_dynamics.html")
   ("Tempo/Duration" "fomus/07_01_03_tempo-duration.html")
   ("Ornamentations" "fomus/07_01_04_ornamentations.html")
   ("Effects" "fomus/07_01_05_effects.html")
   ("Text" "fomus/07_01_06_text.html")
   ("Notation" "fomus/07_01_07_notation.html")
   ("Other" "fomus/07_01_08_other.html")
   ("Timesig properties" "fomus/07_02_00_timesig-properties.html")
   ("Part Properties" "fomus/07_03_00_part-properties.html")
   ("Data" "fomus/08_01_00_data.html")
   ("Lilypond" "fomus/08_02_00_lilypond.html")
   ("Alphabetical Listing of LilyPond Options" "fomus/08_02_01_alphabetical-listing-of-lilypond-options.html")
   ("MusicXML" "fomus/08_03_00_musicxml.html")
   ("Alphabetical Listing of MusicXML Options" "fomus/08_03_01_alphabetical-listing-of-musicxml-options.html")
   ("MusicXML for Sibelius" "fomus/08_04_00_musicxml-for-sibelius.html")
   ("MusicXML for Finale" "fomus/08_05_00_musicxml-for-finale.html")
   ("Common Music Notation" "fomus/08_06_00_common-music-notation.html")
   ("Alphabetical Listing of CMN Options" "fomus/08_06_01_alphabetical-listing-of-cmn-options.html")
   ("MIDI" "fomus/08_07_00_midi.html")
   ("alphabetical listing of midi options" "fomus/08_07_01_alphabetical-listing-of-midi-options.html")
   ("Chunk" "fomus/08_08_00_chunk.html")
   ("Lisp Examples" "fomus/10_01_00_lisp-examples.html")
   ("Simple Example" "fomus/10_01_00_lisp-examples.html")
   ("Staccato and Accent Marks" "fomus/10_01_02_staccato-and-accent-marks.html")
   ("Quartertones" "fomus/10_01_03_quartertones.html")
   ("Polyphony with Slurs" "fomus/10_01_04_polyphony-with-slurs.html")
   ("Piano Chords" "fomus/10_01_05_piano-chords.html")
   ("Quantizing/Chords" "fomus/10_01_06_quantizing-chords.html")
   ("Mark Objects" "fomus/10_01_07_mark-objects.html")
   ("Percussion 1" "fomus/10_01_08_percussion-1.html")
   ("Percussion 2" "fomus/10_01_09_percussion-2.html")
   ("Percussion with Automatic Durations" "fomus/10_01_10_percussion-with-automatic-durations.html")
   ("Semi-Orchestra Score" "fomus/10_01_11_semi-orchestra-score.html")
   ("Key Signatures" "fomus/10_01_12_key-signatures.html")
   ("Chunks" "fomus/10_01_13_chunks.html")
   ("Common Music Examples" "fomus/10_02_00_common-music-examples.html")
   ("2 Part Polyphony" "fomus/10_02_00_common-music-examples.html")
   ("2 Part Polyphony (FOMUS Chooses the Voice)" "fomus/10_02_02_2-part-polyphony-fomus-chooses-the-voice.html")
   ("3 Part Polyphony" "fomus/10_02_03_3-part-polyphony.html")
   ("6 Part Polyphony" "fomus/10_02_04_6-part-polyphony.html")
   ("Text Input File Examples" "fomus/10_03_00_text-input-file-examples.html")
   ("Text Input Commands (From Lisp)" "fomus/10_03_01_text-input-commands-from-lisp.html")
   ("Text Input Commands (Command Line)" "fomus/10_03_02_text-input-commands-command-line.html")
   ("Simple Text Input Example" "fomus/10_03_03_simple-text-input-example.html")
   ("Staccato and Accent Marks" "fomus/10_03_04_staccato-and-accent-marks.html")
   ("Percussion" "fomus/10_03_05_percussion.html")
   ("Articulations" "fomus/10_03_06_articulations.html")
   ("More Percussion" "fomus/10_03_07_more-percussion.html")
   ("Overtone Series (using Quartertones)" "fomus/10_03_08_overtone-series-using-quartertones.html")
   ("Marks 1" "fomus/10_03_09_marks-1.html")
   ("Marks 2" "fomus/10_03_10_marks-2.html")
))
