(mapcar
 (lambda (entry)
   (let ((symbol (intern (car entry)
			 *clamps-overview-symbols*)))
     (if (boundp symbol)
	 (push (cadr entry) (symbol-value symbol))
       (set symbol (cdr entry)))))
 '(
   ("What is Clamps?" "clamps/01_00_introduction.html")
   ("Why Clamps?" "clamps/01_02_why-clamps.html")
   ("External components of Clamps" "clamps/01_03_external-components-of-clamps.html")
   ("Internal Components of Clamps" "clamps/01_04_internal-components-of-clamps.html")
   ("Linux" "clamps/02_00_installation.html")
   ("OSX" "clamps/02_02_osx.html")
   ("Context Help" "clamps/04_00_tools.html")
   ("Finding Source Definitions" "clamps/04_02_finding-source-definitions.html")
   ("Code Inspection" "clamps/04_03_code-inspection.html")
   ("Debugging Tools" "clamps/04_04_debugging-tools.html")
   ("Online Help System" "clamps/04_05_online-help-system.html")
))
