(mapcar
 (lambda (entry)
   (let ((symbol (intern (car entry)
			 *common-music-symbols*)))
     (if (boundp symbol)
	 (push (cadr entry) (symbol-value symbol))
       (set symbol (cdr entry)))))
 '(
   ("add-sfz-preset" "clamps-dict/a-b.html")
   ("ats->browser" "clamps-dict/ats->browser.html")
   ("ct2fr" "clamps-dict/c-d.html")
   ("clamps" "clamps-dict/clamps.html")
   ("clamps-base-url" "clamps-dict/clamps-base-url.html")
   ("clamps-restart-gui" "clamps-dict/clamps-restart-gui.html")
   ("clamps-gui-root" "clamps-dict/clamps-gui-root.html")
   ("ensure-sfz-preset" "clamps-dict/e.html")
   ("ftom" "clamps-dict/f.html")
   ("fr2ct" "clamps-dict/fr2ct.html")
   ("get-sfz-preset" "clamps-dict/g-h.html")
   ("idump" "clamps-dict/i-k.html")
   ("list-sfz-presets" "clamps-dict/l.html")
   ("load-sfz-preset" "clamps-dict/load-sfz-preset.html")
   ("lsample" "clamps-dict/lsample.html")
   ("mtof" "clamps-dict/m.html")
   ("n-lin" "clamps-dict/n-o.html")
   ("n-exp" "clamps-dict/n-exp.html")
   ("node-free-unprotected" "clamps-dict/node-free-unprotected.html")
   ("play-sfz" "clamps-dict/p-q.html")
   ("play-sfz-loop" "clamps-dict/play-sfz-loop.html")
   ("play-sfz-one-shot" "clamps-dict/play-sfz-one-shot.html")
   ("plot" "clamps-dict/plot.html")
   ("remove-sfz-preset" "clamps-dict/r.html")
   ("reset-logger-stream" "clamps-dict/reset-logger-stream.html")
   ("rts?" "clamps-dict/rts.html")
   ("rts" "clamps-dict/rts-1.html")
   ("rts-hush" "clamps-dict/rts-hush.html")
   ("set-bpm" "clamps-dict/s-z.html")
   ("set-tempo" "clamps-dict/set-tempo.html")
   ("set-standard-pitch" "clamps-dict/set-standard-pitch.html")
   ("sfz" "clamps-dict/sfz.html")
   ("sfz-amplitude" "clamps-dict/sfz-amplitude.html")
   ("sfz-chan" "clamps-dict/sfz-chan.html")
   ("sfz-duration" "clamps-dict/sfz-duration.html")
   ("sfz-get-range" "clamps-dict/sfz-get-range.html")
   ("sfz-keynum" "clamps-dict/sfz-keynum.html")
   ("sfz-pan" "clamps-dict/sfz-pan.html")
   ("sfz-preset-file" "clamps-dict/sfz-preset-file.html")
   ("sfz-preset-loaded?" "clamps-dict/sfz-preset-loaded.html")
   ("sfz-play-fn" "clamps-dict/sfz-play-fn.html")
   ("sfz-preset" "clamps-dict/sfz-preset.html")
   ("sfz-startpos" "clamps-dict/sfz-startpos.html")
   ("\ast{}standard-pitch\ast{}" "clamps-dict/standard-pitch.html")
   ("svg" "clamps-dict/svg.html")
   ("svg->browser" "clamps-dict/svg->browser.html")
   ("m-lin" "clamps-dict/.html")
   ("m-exp" "clamps-dict/m-exp.html")
   ("lin-n" "clamps-dict/lin-n.html")
   ("exp-n" "clamps-dict/exp-n.html")
   ("r-elt" "clamps-dict/r-elt.html")
   ("n-exp-dev" "clamps-dict/n-exp-dev.html")
   ("n-lin-dev" "clamps-dict/n-lin-dev.html")
   ("plot-2d" "clamps-dict/plot-2d.html")
   ("plot-3d" "clamps-dict/plot-3d.html")
))
