(mapcar
     (lambda (entry)
       (let ((symbol (intern (car entry)
                     *common-music-symbols*)))
         (if (boundp symbol)
    	 (push (cadr entry) (symbol-value symbol))
           (set symbol (cdr entry)))))
     '(
   ("ats->browser" "clamps-dict/01_00_00_a---b.html")
   ("clamps" "clamps-dict/02_00_00_c---h.html")
   ("clamps-base-url" "clamps-dict/02_02_00_clamps-base-url.html")
   ("clamps-restart-gui" "clamps-dict/02_03_00_clamps-restart-gui.html")
   ("clamps-gui-root" "clamps-dict/02_04_00_clamps-gui-root.html")
   ("idump" "clamps-dict/03_00_00_i---m.html")
   ("node-free-unprotected" "clamps-dict/04_00_00_n---q.html")
   ("reset-logger-stream" "clamps-dict/05_00_00_r.html")
   ("rts?" "clamps-dict/05_02_00_rts.html")
   ("rts" "clamps-dict/05_03_00_rts.html")
   ("rts-hush" "clamps-dict/05_04_00_rts-hush.html")
   ("set-bpm" "clamps-dict/06_00_00_s---z.html")
   ("set-tempo" "clamps-dict/06_02_00_set-tempo.html")
   ("svg->browser" "clamps-dict/06_03_00_svg->browser.html")
))
