(defvar *clamps-doc-symbols*)
(setq *clamps-doc-symbols* (make-vector 63 0))
(mapcar
 (lambda (entry)
   (let ((symbol (intern (car entry)
  			 *clamps-doc-symbols*)))
     (if (boundp symbol)
  	 (push (cadr entry) (symbol-value symbol))
       (set symbol (cdr entry)))))
 '(
   ("Package Naming" "clamps/01_00_00_general.html")
   ("clamps" "clamps/01_02_00_clamps.html")
   ("Startup" "clamps/01_02_00_clamps.html")
   ("Emacs Shortcuts" "clamps/01_02_02_emacs-shortcuts.html")
   ("GUI" "clamps/01_02_03_gui.html")
   ("Meter Display" "clamps/01_02_04_meter-display.html")
   ("Symbols" "clamps/01_02_05_symbols.html")
   ("cl-midictl" "clamps/02_00_00_midi.html")
   ("Receiving and handling MIDI Input" "clamps/02_01_01_receiving-and-handling-midi-input.html")
   ("Exported Symbols" "clamps/02_01_02_exported-symbols.html")
   ("clog-midi-controller" "clamps/02_02_00_clog-midi-controller.html")
   ("cm-svg" "clamps/03_00_00_cm-extensions.html")
   ("cm-svg.rts" "clamps/03_02_00_cm-svg.rts.html")
   ("cm-sfz" "clamps/03_03_00_cm-sfz.html")
   ("cm-poolevt" "clamps/03_04_00_cm-poolevt.html")
   ("cm-poolplayer" "clamps/03_05_00_cm-poolplayer.html")
   ("cm-fomus" "clamps/03_06_00_cm-fomus.html")
   ("cm-incudine" "clamps/03_07_00_cm-incudine.html")
   ("cm-all" "clamps/03_08_00_cm-all.html")
   ("General Incudine Setup" "clamps/04_00_00_incudine-extensions.html")
   ("of-incudine-dsps" "clamps/04_02_00_of-incudine-dsps.html")
   ("incudine-bufs" "clamps/04_03_00_incudine-bufs.html")
   ("General GUI Setup" "clamps/05_00_00_gui.html")
   ("clog-dsp-widgets" "clamps/05_02_00_clog-dsp-widgets.html")
   ("ats-cuda-display" "clamps/05_03_00_ats-cuda-display.html")
   ("cuda-usocket-osc" "clamps/06_00_00_networking.html")
   ("fudi" "clamps/06_02_00_fudi.html")
   ("ats-cuda" "clamps/07_00_00_misc-packages.html")
   ("cl-refs" "clamps/07_02_00_cl-refs.html")
   ("A short example" "clamps/07_02_01_a-short-example.html")
   ("The ref-object class" "clamps/07_02_02_the-ref-object-class.html")
   ("Defining relations" "clamps/07_02_03_defining-relations.html")
   ("cl-sfz" "clamps/07_03_00_cl-sfz.html")
   ("cl-poolplayer" "clamps/07_04_00_cl-poolplayer.html")
   ("plot" "clamps/07_05_00_plot.html")
   ("cm-utils" "clamps/07_06_00_cm-utils.html")
   ("orm-utils" "clamps/07_07_00_orm-utils.html")
   ))
